name: H6060 Experiment 1 - Pillow

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  security-events: write

jobs:
  build-application:
    name: Build application
    runs-on: ubuntu-latest
    steps:
        # Branched from tag 8.3.0
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Install Python 3.7
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.7

      - name: Install Dependencies
        env:
          GHA_PYTHON_VERSION: 3.7
        run: .ci/install.sh

      - name: Build And Upload Python Package
        uses: seansmith39/H6060-Experiment-Resources/.github/actions/python/python-build-upload@main
        with:
          build-command: .ci/build.sh
          build-directory: build

      - name: Run Tests
        env:
          PYTHONOPTIMIZE: 2
        run: xvfb-run -s '-screen 0 1024x768x24' .ci/test.sh

      - name: Upload Coverage XML Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: error

  python-scanning:
    name: Run SCA and SAST Python Scanning Workflow
    uses: seansmith39/H6060-Experiment-Resources/.github/workflows/experiment-1-python.yml@main
    needs: build-application
    secrets: inherit
    with:
      project-name: H6060-Python-pillow
      project-build-dir: build
      eclipse-steady-workspace-token: 1A8CC68377BFEEA81CDF80CFA757872E
      eclipse-steady-project-source-directories: src